import Config

# Configure your database
config :campaigns_api, CampaignsApi.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "campaigns_api_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :campaigns_api, CampaignsApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "b0q388bfUZUXPiFyG+nZsINFFRj6tVkmhMHjQSKSleYeZdQ2VjL9fkAXjmQRZ69z",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :campaigns_api, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Keycloak configuration for development
# For development, using a simple secret. In production, use JWKS URL
config :campaigns_api,
  jwt_secret: "dev-secret-key-change-in-production",
  keycloak_jwks_url: System.get_env("KEYCLOAK_JWKS_URL")

# PromEx configuration
config :campaigns_api, CampaignsApi.PromEx,
  disabled: false,
  manual_metrics_start_delay: :no_delay,
  drop_metrics_groups: [],
  grafana: [
    host: System.get_env("GRAFANA_HOST") || "http://localhost:3000",
    auth_token: System.get_env("GRAFANA_TOKEN"),
    upload_dashboards_on_start: false,
    folder_name: "CampaignsAPI",
    annotate_app_lifecycle: true
  ],
  metrics_server: :disabled

# OpenTelemetry configuration for development
config :opentelemetry,
  resource: [
    service: [
      name: "campaigns_api",
      namespace: "rewards_api"
    ]
  ],
  span_processor: :batch,
  traces_exporter: :otlp

config :opentelemetry_exporter,
  otlp_protocol: :grpc,
  otlp_endpoint: "http://localhost:4317",
  otlp_headers: [],
  otlp_compression: :gzip

# Configure logger to include OpenTelemetry metadata
config :logger, :console,
  format: "[$level] $message $metadata\n",
  metadata: [:request_id, :trace_id, :span_id]
